#!/usr/bin/env python3
"""Regenerate microsites/index.html + microsites/_index.json.

Walks `microsites/<slug>/index.html`, extracts the <title> and the
first `<p class="tagline">` or `<p class="subtitle">` it finds, and
writes:

    microsites/_index.json — [{ slug, title, subtitle, mtime, url }]
    microsites/index.html  — directory-index landing page (served by
                             GitHub Pages at /microsites/).

Hidden / underscore-prefixed slugs are skipped (e.g. `_template`).
Idempotent. Stdlib only — no third-party deps so the GitHub Action
runs on the stock setup-python image without `pip install`.

Usage:
    python3 scripts/build_microsites_index.py
"""

from __future__ import annotations

import datetime as _dt
import json
import re
from html import escape
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MICROSITES_DIR = REPO_ROOT / "microsites"
PUBLIC_BASE = "https://fidel-perez.github.io/portfolio/microsites"


def _extract(html: str, pattern: str) -> str | None:
    m = re.search(pattern, html, re.IGNORECASE | re.DOTALL)
    if not m:
        return None
    return re.sub(r"\s+", " ", m.group(1)).strip()


def _scan() -> list[dict]:
    if not MICROSITES_DIR.exists():
        return []
    entries: list[dict] = []
    for child in sorted(MICROSITES_DIR.iterdir()):
        if not child.is_dir() or child.name.startswith(("_", ".")):
            continue
        index = child / "index.html"
        if not index.exists():
            continue
        html = index.read_text(errors="replace")
        title = _extract(html, r"<title>([^<]+)</title>") or child.name
        subtitle = (
            _extract(html, r'<p class="tagline">([^<]+)</p>')
            or _extract(html, r'<p class="subtitle">([^<]+)</p>')
            or ""
        )
        entries.append(
            {
                "slug": child.name,
                "title": title,
                "subtitle": subtitle[:200],
                "mtime": _dt.datetime.fromtimestamp(index.stat().st_mtime).isoformat(
                    timespec="seconds"
                ),
                "url": f"{PUBLIC_BASE}/{child.name}/",
            }
        )
    return entries


HTML_TEMPLATE = """<!doctype html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Per-target microsites — Fidel Perez Portfolio</title>
<meta name="description" content="Index of per-target microsites generated by my agent platform. Each one was tailored to a specific company.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600;700&display=swap" rel="stylesheet">
<style>
  :root {{
    --bg: #f8fafc; --bg-elev: #ffffff; --fg: #0d1220;
    --fg-muted: #475066; --accent: #3b82f6; --accent-soft: #dbeafe;
    --rule: #e2e8f0; --grid: rgba(226,232,240,0.5);
    --font-body: "DM Sans", system-ui, sans-serif;
    --font-mono: "JetBrains Mono", ui-monospace, monospace;
  }}
  * {{ box-sizing: border-box; }}
  body {{ margin: 0; font-family: var(--font-body); color: var(--fg); background: var(--bg); }}
  body::before {{
    position: fixed; inset: 0; z-index: 0; pointer-events: none; content: "";
    background-image: linear-gradient(var(--grid) 1px, transparent 1px),
                      linear-gradient(90deg, var(--grid) 1px, transparent 1px);
    background-size: 40px 40px;
  }}
  main {{ position: relative; z-index: 1; max-width: 880px; margin: 0 auto; padding: 4rem 1.5rem; }}
  h1 {{ font-size: clamp(2rem, 4vw, 2.6rem); margin: 0 0 0.5rem; }}
  .lead {{ color: var(--fg-muted); max-width: 38em; margin: 0 0 2rem; }}
  .meta {{ font-family: var(--font-mono); font-size: 0.78rem; color: var(--fg-muted); margin-bottom: 2rem; }}
  ul.entries {{ list-style: none; padding: 0; margin: 0; display: grid; gap: 1rem; }}
  ul.entries li {{
    background: var(--bg-elev); border: 1px solid var(--rule); border-left: 3px solid var(--accent);
    border-radius: 0 12px 12px 0; padding: 1rem 1.25rem;
  }}
  ul.entries a.title {{ font-size: 1.1rem; font-weight: 600; color: var(--accent); text-decoration: none; }}
  ul.entries a.title:hover {{ text-decoration: underline; }}
  ul.entries .sub {{ color: var(--fg-muted); font-size: 0.95rem; margin: 0.4rem 0 0.6rem; }}
  ul.entries .stamp {{ font-family: var(--font-mono); font-size: 0.75rem; color: #94a3b8; }}
  .footer {{ margin-top: 3rem; font-family: var(--font-mono); font-size: 0.78rem; color: var(--fg-muted); }}
  .footer a {{ color: var(--accent); }}
</style>
</head>
<body>
<main>
  <h1>Per-target microsites</h1>
  <p class="lead">Each page below was auto-generated by an agent platform I built for a single outreach target. The platform is private; the artefacts are public — they are the proof.</p>
  <p class="meta">Generated {generated_at} · {count} pages</p>
  {body}
  <p class="footer">← <a href="../">back to portfolio</a> · source: <a href="https://github.com/fidel-perez/portfolio">github.com/fidel-perez/portfolio</a></p>
</main>
</body>
</html>
"""


def _render_html(entries: list[dict]) -> str:
    if entries:
        items = "\n".join(
            (
                "  <li>\n"
                f'    <a class="title" href="./{escape(e["slug"])}/" rel="noopener">{escape(e["title"])}</a>\n'
                f'    <p class="sub">{escape(e["subtitle"])}</p>\n'
                f'    <span class="stamp">{escape(e["slug"])} · build {escape(e["mtime"])}</span>\n'
                "  </li>"
            )
            for e in entries
        )
        body = f'<ul class="entries">\n{items}\n</ul>'
    else:
        body = '<p class="lead"><em>No microsites yet.</em></p>'
    return HTML_TEMPLATE.format(
        body=body,
        count=len(entries),
        generated_at=_dt.date.today().isoformat(),
    )


def regenerate() -> int:
    entries = _scan()
    MICROSITES_DIR.mkdir(parents=True, exist_ok=True)
    json_path = MICROSITES_DIR / "_index.json"
    html_path = MICROSITES_DIR / "index.html"
    json_path.write_text(json.dumps(entries, indent=2) + "\n")
    html_path.write_text(_render_html(entries))
    print(f"[ok] {len(entries)} entries -> {json_path.name}, {html_path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(regenerate())
